name: Six One Six Vision Center
favicon: null
layout_spectrum: 0.3043873505666852
typography_spectrum: 0.24656869936734438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6826583161018789
  lightness: 0.20595495076850057
  saturation: 0.42801209865137935
  rhythmicContrast: 0.05952805723063648
purpose: []
